### ISSUE TITLE
Full-text search

### ISSUE THREAD

**Issue by windymindy** [ss89/docker-rhodecode-ce#1]
Is there a way to enable cron-like way of index update in rhodecode docker?
https://docs.rhodecode.com/RhodeCode-Enterprise/admin/indexing.html#indexing-ref

**Comment by ss89** [comment]
Sorry for getting back to you so late, the message got into my spam folder.
I currently don't have RhodeCode Tools in my image, but am evaluating a way to have it, so you can have an even more powerful RhodeCode Container.

**Comment by ss89** [comment]
i have created a rhodecode tools wrapper that will be in the next 4.12.4 build.
The instance in the container is always enterprise-1.
You can use any of the rhodecode-tools that you would usually call with "rhodecode-tools" with 
`docker exec yourContainerId rhodecode tools index --instance-name 'enterprise-1'`
`docker exec yourContainerId rhodecode api ...`
etc.

**Comment by ss89** [comment]
build is now starting: https://hub.docker.com/r/sstruss/rhodecode-ce/builds/bttclocpyn7nzxrzxyvhtez/

**Comment by ss89** [comment]
closed because of inactivity
