### ISSUE TITLE
Error in building

### ISSUE THREAD

**Issue by k-guilloux** [ss89/docker-rhodecode-ce#3]
This error appears when building the image :

`  File "/tmp/nix-build-python2.7-configparser-4.0.2.drv-0/easy_install-WDS8no/setuptools_scm-6.0.1/src/setuptools_scm/utils.py", line 41
    print(*k)
          ^
SyntaxError: invalid syntax
builder for '/nix/store/rrfw1xvfadnimhx0q86z7r2mlz8l79j0-python2.7-configparser-4.0.2.drv' failed with exit code 1
`

`The command '/bin/sh -c USER=root . /root/.nix-profile/etc/profile.d/nix.sh &&         cd rhodecode-develop/rhodecode-tools-ce &&         nix-she
ll' returned a non-zero code: 100
`

**Comment by ss89** [comment]
Which branch were you on? Can you also post more output? Maybe the last 100-200 lines?

**Comment by marcin-kuzminski** [comment]
It's a known issue. The recent python package updated broken builds. We're working on set of fixes for the next release for our docker repo.

**Comment by ss89** [comment]
Awesome, thanks for helping out @marcin-kuzminski

**Comment by ss89** [comment]
Closing the issue because it is not related to the docker image, but to a known python package build error
